name: Sync Tailscale ACLs

on:
  push:
    branches: [ main ]
    paths: [ "policy.hujson" ]
  workflow_dispatch:

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Deploy ACL
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply
