[ssh.paul]
phos = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEExkUZoKMEE0mf5JY0gcFJEYj+wUCk+k+s1NY7rlhdR paul@phos"
github = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIoeuEWVgRmYLezPmjKicdk6rYfMOwswFz3GRx5oXzBv paul1365972@gmail.com"
opencode = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK1JDeFJdeYjjRICEQbuqGDr+nf9Tc9f9ZnaK+t/4dIY paul1365972@gmail.com"
geomesh-hetzner = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAQd4Ysy+n65f6w9uf4/JaBYscw0gnJsfxQgh41E0Oif paul@geomesh-hetzner"
